export default {
    LOGIN: "LOGIN",
    SIGNUP:"SIGNUP",
    //SupAdmin
    DELETE:"DELETE",
    SHOW_ALL_ADMIN:"SHOW_ALL_ADMIN",
    ACTIVEADMIN:"ACTIVEADMIN",
    DESACTIVEADMIN:"DESACTIVEADMIN",
    SORTADMINRATING:"SORTADMINRATING",
    SORTADMINCLIENT:"SORTADMINCLIENT",
    ADDADMIN:"ADDADMIN",
    CLEAR_REDUX_STATE: "CLEAR_REDUX_STATE",
    EDITADMIN:"EDITADMIN",
    ADMIN_ALPHABITIC_ORDER:"ADMIN_ALPHABITIC_ORDER",


    //Admin
    UPDATEADMINLOCATION :"UPDATEADMINLOCATION ",
       //Client Part
        DELETECLIENT:"DELETECLIENT",
        SHOW_ALL_CILENTS :"SHOW_ALL_CILENTS ", 
        EDITCLIENT:"EDITCLIENT",
        ADDCLIENT:"ADDCLIENT",
        SORTCLIENT:"SORTCLIENT"  ,
        // SORTCLIENTALPHABITIC:"SORTCLIENTALPHABITIC",
        //Agent Part
        SHOW_ALL_AGENTS:"SHOW_ALL_AGENTS" , 
        DELETEAGENT:"DELETEAGENT" ,
        ADDAGENT:"ADDAGENT",
        ACTIVEAGENT:"ACTIVEAGENT" ,
        DESACTIVEAGENT:"DESACTIVEAGENT", 
        EDITAGENT:"EDITAGENT" ,
        //Visit Part
        ADDVISIT:"ADDVISIT" ,
        ShOWALLCLIENTVISITS:"ShOWALLCLIENTVISITS",
        ShOWALLCLIENTVISITS_THISMONTH:"ShOWALLCLIENTVISITS_THISMONTH",
        DELETEVISIT:"DELETEVISIT",
        ShOWALLCLIENTVISITS_THISWEEK:"ShOWALLCLIENTVISITS_THISWEEK",
        ShOWALLCLIENTVISITS_THISYEAR:"ShOWALLCLIENTVISITS_THISYEAR",
        EDITVISIT:"EDITVISIT",
        VISIT_DONE:"VISIT_DONE",
        VISIT_UNDONE:"VISIT_UNDONE",
        //Intervention Part
        ADDINTERVENTION:"ADDINTERVENTION",
        SHOW_ALL_INTERVENTION:"SHOW_ALL_INTERVENTION",
        //recette 
        ADDRecette:"ADDRecette",
        UpdateRecette:"UpdateRecette",
        ExistRecette:"ExistRecette",
    //Guest
    SHOW_NEAREST_VET:"SHOW_NEAREST_VET",
    //Client
    UPDATERATING:"UPDATERATING",
    //Agent
    SHOW_ALL_INTERVENTION_AGENT:"SHOW_ALL_INTERVENTION_AGENT",
    SHOW_ALL_INTERVENTION_THISYEAR:"SHOW_ALL_INTERVENTION_THISYEAR",
    SHOW_ALL_INTERVENTION_THISMONTH:'SHOW_ALL_INTERVENTION_THISMONTH',
    SHOW_ALL_INTERVENTION_THISWEEK:"SHOW_ALL_INTERVENTION_THISWEEK",
    SHOW_ALL_INTERVENTION_TODAY:"SHOW_ALL_INTERVENTION_TODAY",
    //client
    ADDLIKE:"ADDLIKE",
    LIKED:"LIKED",
}